apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: smartfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: smartfood-restaurant:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: smartfood-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: smartfood-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartfood-secrets
                  key: DB_PASSWORD
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: smartfood-config
                  key: EUREKA_URL
            - name: JWT_PUBLIC_KEY_PATH
              value: file:/app/keys/public.pem
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: smartfood-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: smartfood-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: smartfood-secrets
                  key: CLOUDINARY_API_SECRET
          volumeMounts:
            - name: jwt-keys
              mountPath: /app/keys
              readOnly: true
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 10
      volumes:
        - name: jwt-keys
          secret:
            secretName: smartfood-secrets
            items:
              - key: JWT_PUBLIC_KEY
                path: public.pem
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: smartfood
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 8082
      targetPort: 8082