ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;

ALTER TABLE orders ADD CONSTRAINT orders_status_check
CHECK (status IN ('PENDING', 'RESERVED', 'PAID', 'CONFIRMED', 'FAILED', 'REJECTED', 'READY', 'PICKED_UP'));