server:
  port: 8085

spring:
  application:
    name: pricing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/smartfood
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update                # only for local dev; will replace with Flyway later
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9094   # note your custom port
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app:
  kafka:
    topics:
      price-updated: price-updated    # topic for PriceUpdatedEvent

  pricing:
    schedule: "0 */5 * * * *"        # every 5 minutes
    mcp-url: ${MCP_AI_AGENT_BASE_URL:http://localhost:8000}/mcp/tools/call


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus